#!/bin/bash
clear
[[ "$(whoami)" != "root" ]] && {
echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33mvocê precisa executar como root\033[0m"
rm $HOME/Plus > /dev/null 2>&1; exit 0
}
_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r'| sed -e 's/[^a-z.]//ig'| rev); _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
cd $HOME
fun_bar () {
comando[0]="$1"
comando[1]="$2"
(
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
) > /dev/null 2>&1 &
tput civis
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
while true; do
for((i=0; i<18; i++)); do
echo -ne "\033[1;31m#"
sleep 0.1s
done
[[ -e $HOME/fim ]] && rm $HOME/fim && break
echo -e "\033[1;33m]"
sleep 1s
tput cuu1
tput dl1
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
function verif_key () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
[[ ! -e "$_Ink/list" ]] && {
echo -e "\n\033[1;31mKEY INVÁLIDA!\033[0m"
rm -rf $HOME/Plus > /dev/null 2>&1
sleep 2
clear; exit 1
}
}
echo -e "  ██████╗ ███████╗███████╗
          ██╔═══██╗██╔════╝██╔════╝
          ██║   ██║█████╗  █████╗  
          ██║   ██║██╔══╝  ██╔══╝  
          ╚██████╔╝██║     ██║     
           ╚═════╝ ╚═╝     ╚═╝"     
                        
echo -e "\e[1;31m=================================================="
echo -e "\e[0;37m 𝑺𝒄𝒓𝒊𝒑 𝑭𝒓𝒆𝒆 𝒔𝒔𝒉 𝒅𝒆𝒔𝒂𝒕𝒊𝒗𝒂𝒅𝒐 𝒅𝒆𝒇𝒊𝒏𝒊𝒕𝒊𝒗𝒂𝒎𝒆𝒏𝒕𝒆"
echo -e "\e[1;31m==================================================\033[0m"
done
echo ""
echo -e "        \033[1;33m • \033[1;32mPROGRAMA FINALIZADO\033[1;33m • \033[0m"
