#!/bin/bash
#Menu Adaptado Base ADM Con Utilitarios

# Utilitarios
wget -O /bin/criarpay https://raw.githubusercontent.com/Jeffssha/NET-WORLD/main/SSHPLUS/criarpay; chmod +x /bin/criarpay
wget -O /bin/fai2ban https://raw.githubusercontent.com/Jeffssha/NET-WORLD/main/SSHPLUS/fai2ban; chmod +x /bin/fai2ban
wget -O /bin/paysnd https://raw.githubusercontent.com/Jeffssha/NET-WORLD/main/SSHPLUS/paysnd; chmod +x /bin/paysnd
wget -O /bin/squidcache https://raw.githubusercontent.com/Jeffssha/NET-WORLD/main/SSHPLUS/squidcache; chmod +x /bin/squidcache
wget -O /bin/tcpspeed https://raw.githubusercontent.com/Jeffssha/NET-WORLD/main/SSHPLUS/tcpspeed; chmod +x /bin/tcpspeed
wget -O /bin/ultrahost https://raw.githubusercontent.com/Jeffssha/NET-WORLD/main/SSHPLUS/ultrahost; chmod +x /bin/ultrahost
wget -O /bin/vncinstall https://raw.githubusercontent.com/Jeffssha/NET-WORLD/main/SSHPLUS/vncinstall; chmod +x /bin/vncinstall

# Menu Utilitarios
wget -O /bin/utilitarios https://raw.githubusercontent.com/Jeffssha/NET-WORLD/main/SSHPLUS/utilitarios; chmod +x /bin/utilitarios
#fim
