#!/bin/bash
#create by: Camilo Orrego Oficial - Youtube - Channel
#20/10/20
clear
sleep 2.5
cowsay -f eyes  NET-FREE | lolcat
echo -e "\e[1;31m======================================================"
figlet NET-FREE | lolcat
echo -e "\e[0;35m   by: @Jeffssh - Grupo no Telegram:@netword2020      "
echo -e "\e[1;31m======================================================"
echo ""
echo -e "\033[1;32mɴᴀᴏ ᴠᴇɴᴅᴀ ᴇsᴛᴇ ᴍᴇᴛᴏᴅᴏ \033[1;37m"
echo -e "\033[1;32mɴᴀᴏ sᴇᴊᴀ ʙᴜʀʀᴏ ɴᴀᴏ ᴅɪᴠᴜʟɢᴜᴇ ɴᴏ ʏᴏᴜᴛᴜʙᴇ\033[1;37m"
echo ""
echo -e "\e[1;31m[!]\033[1;32mINTRUCÕES"
echo -e "\e[1;31m[!]\033[1;32mMB'S PARA OPERADORA VIVO PÉ-PAGO"
echo -e "\e[1;31m[!]\033[1;32mO CHIP TEM QUE ESTA SEM SALDO NENHUM"
echo -e "\033[1;92mTRUE = APROVADO\033\033[1;92m  \033[1;31mFALSE = REPROVADO\033[1;31m"
echo ""
echo -e "\033[0m\033[01;37m• \033[01;33mGERAR MB'S \033[0m\033[01;37m•\033[0m"
sleep 1
echo -e "\033[01;32mINFORME SEU NÚMERO DDD+NÚMERO\033[01;37m"
read NUMERO
echo -e "\033[01;32mQUANTAS VEZES DESEJA REPETIR?\033[1;37m"
read VEZES
echo ""
echo -e "\033[0m\033[01;33mINICIANDO TOKEN 1\033[03;037m"
for i in $(seq $VEZES);
do
data=$"msisdn=$NUMERO&campid=949e575a-6db8-4608-8b71-1281e6e506df&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
echo -e "\033[0m\033[01;32mCONTAGEM:\033[01;37m$i\033[03;037m"
done
echo -e ""
echo -e "\033[0m\033[01;33mINICIANDO TOKEN 2\033[03;037m"
for i in $(seq $VEZES);
do
data=$"msisdn=$NUMERO&campid=04e564c7-f410-49f5-8dee-b268eaef5223&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
echo -e "\033[0m\033[01;32mCONTAGEM:\033[01;37m$i\033[03;037m"
done
echo ""
echo -e "\033[0m\033[01;33mINICIANDO TOKEN 3\033[03;037m"
for i in $(seq $VEZES);
do
data=$"msisdn=$NUMERO&campid=09d15706-7d7a-4127-8f7d-d1c391d016e7&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
echo -e "\033[0m\033[01;32mCONTAGEM:\033[01;37m$i\033[03;037m"
done
echo ""
echo -e "\033[0m\033[01;33mINICIANDO TOKEN 4\033[03;037m"
for i in $(seq $VEZES);
do
data=$"msisdn=$NUMERO&campid=4919b47c-f588-4e71-87e3-639b3af92e4d&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
echo -e "\033[0m\033[01;32mCONTAGEM:\033[01;37m$i\033[03;037m"
done
echo ""
echo -e "\033[0m\033[01;33mINICIANDO TOKEN 5\033[03;037m"
for i in $(seq $VEZES);
do
data=$"msisdn=$NUMERO&campid=02f76cd1-eead-44ff-88dd-aa69538c7aef&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
echo -e "\033[0m\033[01;32mCONTAGEM:\033[01;37m$i\033[03;037m"
done
echo ""
echo -e "\033[0m\033[01;33mINICIANDO TOKEN 5\033[03;037m"
for i in $(seq $VEZES);
do
data=$"msisdn=$NUMERO&campid=19313963-7198-4a33-9511-1c72c7d6152a&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
echo -e "\033[0m\033[01;32mCONTAGEM:\033[01;37m$i\033[03;037m"
done
echo ""
echo -e "        \033[0m\033[01;37m• \033[01;32mPROGRAMA FINALIZADO \033[01;37m•\033[0m"
sleep 5
./net-free
